### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by y3ff18** [CoolerVoid/codecat#15]
An encoding error occurred when clicking on the View function
<img width="770" alt="image" src="https://user-images.githubusercontent.com/74667825/159441223-2ce62e10-4b8e-4065-a368-26b6ff269633.png">
A coding error was reported
![image](https://user-images.githubusercontent.com/74667825/159441348-10b5fc49-efed-42e2-b470-11afe7fd96ae.png)
What I tried to audit was a content management system with Chinese
Thank you for working it out

**Comment by CoolerVoid** [comment]
Thank you for the report, so next weekend I gonna fix that issue.
